# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modRespBinaria_d.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(915, 656)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(20, 0))
        self.label_11.setMaximumSize(QtCore.QSize(1000000, 50))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(81, 16))
        self.label_5.setMaximumSize(QtCore.QSize(81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_pregImag0 = QtWidgets.QPushButton(Form)
        self.btn_pregImag0.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_pregImag0.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_pregImag0.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_preg0.png);")
        self.btn_pregImag0.setText("")
        self.btn_pregImag0.setObjectName("btn_pregImag0")
        self.horizontalLayout_2.addWidget(self.btn_pregImag0)
        self.btn_pregImag50 = QtWidgets.QPushButton(Form)
        self.btn_pregImag50.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_pregImag50.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_pregImag50.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_preg50.png);\n"
"")
        self.btn_pregImag50.setText("")
        self.btn_pregImag50.setObjectName("btn_pregImag50")
        self.horizontalLayout_2.addWidget(self.btn_pregImag50)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setMaximumSize(QtCore.QSize(80, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setMinimumSize(QtCore.QSize(81, 10))
        self.label_14.setMaximumSize(QtCore.QSize(81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_pregAND = QtWidgets.QPushButton(Form)
        self.btn_pregAND.setMinimumSize(QtCore.QSize(51, 31))
        self.btn_pregAND.setMaximumSize(QtCore.QSize(51, 31))
        self.btn_pregAND.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_and.png);")
        self.btn_pregAND.setText("")
        self.btn_pregAND.setObjectName("btn_pregAND")
        self.horizontalLayout_3.addWidget(self.btn_pregAND)
        self.btn_pregOR = QtWidgets.QPushButton(Form)
        self.btn_pregOR.setMinimumSize(QtCore.QSize(51, 31))
        self.btn_pregOR.setMaximumSize(QtCore.QSize(51, 31))
        self.btn_pregOR.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_or.png);")
        self.btn_pregOR.setText("")
        self.btn_pregOR.setObjectName("btn_pregOR")
        self.horizontalLayout_3.addWidget(self.btn_pregOR)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(40, 0))
        self.label_6.setMaximumSize(QtCore.QSize(80, 50))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(91, 16))
        self.label_9.setMaximumSize(QtCore.QSize(91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_pregIzq = QtWidgets.QPushButton(Form)
        self.btn_pregIzq.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_pregIzq.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_pregIzq.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_izquierda.png);\n"
"")
        self.btn_pregIzq.setText("")
        self.btn_pregIzq.setProperty("id", 1)
        self.btn_pregIzq.setObjectName("btn_pregIzq")
        self.horizontalLayout_4.addWidget(self.btn_pregIzq)
        self.btn_pregCen = QtWidgets.QPushButton(Form)
        self.btn_pregCen.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_pregCen.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_pregCen.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_centrar.png);\n"
"")
        self.btn_pregCen.setText("")
        self.btn_pregCen.setProperty("id", 0)
        self.btn_pregCen.setObjectName("btn_pregCen")
        self.horizontalLayout_4.addWidget(self.btn_pregCen)
        self.btn_pregDer = QtWidgets.QPushButton(Form)
        self.btn_pregDer.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_pregDer.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_pregDer.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_derecho.png);")
        self.btn_pregDer.setText("")
        self.btn_pregDer.setProperty("id", 2)
        self.btn_pregDer.setObjectName("btn_pregDer")
        self.horizontalLayout_4.addWidget(self.btn_pregDer)
        self.dSpin_pregTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_pregTam.setMinimumSize(QtCore.QSize(69, 26))
        self.dSpin_pregTam.setMaximumSize(QtCore.QSize(69, 26))
        self.dSpin_pregTam.setObjectName("dSpin_pregTam")
        self.horizontalLayout_4.addWidget(self.dSpin_pregTam)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 50))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setMinimumSize(QtCore.QSize(91, 16))
        self.label_10.setMaximumSize(QtCore.QSize(91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_respIzq = QtWidgets.QPushButton(Form)
        self.btn_respIzq.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_respIzq.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_respIzq.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_izquierda.png);\n"
"")
        self.btn_respIzq.setText("")
        self.btn_respIzq.setProperty("id", 1)
        self.btn_respIzq.setObjectName("btn_respIzq")
        self.horizontalLayout_6.addWidget(self.btn_respIzq)
        self.btn_respCen = QtWidgets.QPushButton(Form)
        self.btn_respCen.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_respCen.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_respCen.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_centrar.png);\n"
"")
        self.btn_respCen.setText("")
        self.btn_respCen.setProperty("id", 0)
        self.btn_respCen.setObjectName("btn_respCen")
        self.horizontalLayout_6.addWidget(self.btn_respCen)
        self.btn_respDer = QtWidgets.QPushButton(Form)
        self.btn_respDer.setMinimumSize(QtCore.QSize(21, 21))
        self.btn_respDer.setMaximumSize(QtCore.QSize(21, 21))
        self.btn_respDer.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/alinear_derecho.png);")
        self.btn_respDer.setText("")
        self.btn_respDer.setProperty("id", 2)
        self.btn_respDer.setObjectName("btn_respDer")
        self.horizontalLayout_6.addWidget(self.btn_respDer)
        self.dSpin_respTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_respTam.setMinimumSize(QtCore.QSize(69, 26))
        self.dSpin_respTam.setMaximumSize(QtCore.QSize(69, 26))
        self.dSpin_respTam.setObjectName("dSpin_respTam")
        self.horizontalLayout_6.addWidget(self.dSpin_respTam)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(40, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 50))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(101, 16))
        self.label_15.setMaximumSize(QtCore.QSize(101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setMinimumSize(QtCore.QSize(101, 31))
        self.timeEdit.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeEdit.setCurrentSectionIndex(0)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_4.addWidget(self.timeEdit, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(40, 50))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.listWidget_panelVersion = QtWidgets.QStackedWidget(Form)
        self.listWidget_panelVersion.setToolTipDuration(0)
        self.listWidget_panelVersion.setStyleSheet("")
        self.listWidget_panelVersion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelVersion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelVersion.setObjectName("listWidget_panelVersion")
        self.verticalLayout_6.addWidget(self.listWidget_panelVersion)

        self.retranslateUi(Form)
        self.listWidget_panelVersion.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Incluir imagenes"))
        self.label_14.setText(_translate("Form", "Tipo pregunta"))
        self.label_9.setText(_translate("Form", "Posicion pregunta"))
        self.label_10.setText(_translate("Form", "Posicion respuesta"))
        self.label_15.setText(_translate("Form", "Tiempo de pregunta"))
        self.timeEdit.setDisplayFormat(_translate("Form", "mm:ss"))
import IMAG_rc
