# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EjecutadorCuestionario_d.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 675)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(40, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bel_respondioEl = QtWidgets.QLabel(Form)
        self.bel_respondioEl.setMinimumSize(QtCore.QSize(50, 16))
        self.bel_respondioEl.setMaximumSize(QtCore.QSize(50, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bel_respondioEl.setFont(font)
        self.bel_respondioEl.setObjectName("bel_respondioEl")
        self.verticalLayout_2.addWidget(self.bel_respondioEl, 0, QtCore.Qt.AlignHCenter)
        self.btn_respondioEl = QtWidgets.QPushButton(Form)
        self.btn_respondioEl.setMinimumSize(QtCore.QSize(41, 41))
        self.btn_respondioEl.setMaximumSize(QtCore.QSize(41, 41))
        self.btn_respondioEl.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_yoNoDije.png);")
        self.btn_respondioEl.setText("")
        self.btn_respondioEl.setObjectName("btn_respondioEl")
        self.verticalLayout_2.addWidget(self.btn_respondioEl, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bel_respondioYo = QtWidgets.QLabel(Form)
        self.bel_respondioYo.setMinimumSize(QtCore.QSize(61, 16))
        self.bel_respondioYo.setMaximumSize(QtCore.QSize(61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bel_respondioYo.setFont(font)
        self.bel_respondioYo.setObjectName("bel_respondioYo")
        self.verticalLayout.addWidget(self.bel_respondioYo, 0, QtCore.Qt.AlignHCenter)
        self.btn_respondioYo = QtWidgets.QPushButton(Form)
        self.btn_respondioYo.setMinimumSize(QtCore.QSize(41, 41))
        self.btn_respondioYo.setMaximumSize(QtCore.QSize(41, 41))
        self.btn_respondioYo.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_yoDije.png);")
        self.btn_respondioYo.setText("")
        self.btn_respondioYo.setObjectName("btn_respondioYo")
        self.verticalLayout.addWidget(self.btn_respondioYo, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(20, 0))
        self.label_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.bel_estadoPregunta = QtWidgets.QLabel(Form)
        self.bel_estadoPregunta.setMinimumSize(QtCore.QSize(70, 70))
        self.bel_estadoPregunta.setMaximumSize(QtCore.QSize(200, 200))
        self.bel_estadoPregunta.setStyleSheet("")
        self.bel_estadoPregunta.setText("")
        self.bel_estadoPregunta.setObjectName("bel_estadoPregunta")
        self.horizontalLayout_2.addWidget(self.bel_estadoPregunta)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(40, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(451, 71))
        self.scrollArea.setMaximumSize(QtCore.QSize(800, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 449, 78))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bel_califFinal = QtWidgets.QLabel(Form)
        self.bel_califFinal.setMinimumSize(QtCore.QSize(91, 31))
        self.bel_califFinal.setMaximumSize(QtCore.QSize(91, 31))
        self.bel_califFinal.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_califFinal.setObjectName("bel_califFinal")
        self.verticalLayout_3.addWidget(self.bel_califFinal, 0, QtCore.Qt.AlignHCenter)
        self.btn_terminar = QtWidgets.QPushButton(Form)
        self.btn_terminar.setMinimumSize(QtCore.QSize(101, 41))
        self.btn_terminar.setMaximumSize(QtCore.QSize(101, 41))
        self.btn_terminar.setObjectName("btn_terminar")
        self.verticalLayout_3.addWidget(self.btn_terminar, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.listWidget_panelPreguntas = QtWidgets.QStackedWidget(Form)
        self.listWidget_panelPreguntas.setMinimumSize(QtCore.QSize(911, 511))
        self.listWidget_panelPreguntas.setToolTipDuration(0)
        self.listWidget_panelPreguntas.setStyleSheet("")
        self.listWidget_panelPreguntas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelPreguntas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelPreguntas.setObjectName("listWidget_panelPreguntas")
        self.verticalLayout_4.addWidget(self.listWidget_panelPreguntas)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.bel_punteroPregunta = QtWidgets.QLabel(Form)
        self.bel_punteroPregunta.setMinimumSize(QtCore.QSize(26, 19))
        self.bel_punteroPregunta.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bel_punteroPregunta.setFont(font)
        self.bel_punteroPregunta.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_punteroPregunta.setObjectName("bel_punteroPregunta")
        self.horizontalLayout.addWidget(self.bel_punteroPregunta)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(15, 25))
        self.label_2.setMaximumSize(QtCore.QSize(15, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.bel_noPreguntas = QtWidgets.QLabel(Form)
        self.bel_noPreguntas.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bel_noPreguntas.setFont(font)
        self.bel_noPreguntas.setStyleSheet("")
        self.bel_noPreguntas.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_noPreguntas.setObjectName("bel_noPreguntas")
        self.horizontalLayout.addWidget(self.bel_noPreguntas)
        self.btn_prev = QtWidgets.QPushButton(Form)
        self.btn_prev.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_prev.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_prev.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen5_prevE.png);\n"
"  }\n"
"QPushButton:hover {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen4_prevD .png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen5_prevE.png);\n"
"}\n"
"")
        self.btn_prev.setText("")
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout.addWidget(self.btn_prev)
        self.btn_next = QtWidgets.QPushButton(Form)
        self.btn_next.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_next.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_next.setStyleSheet("QPushButton {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen5_nextE.png);  }\n"
"\n"
"QPushButton:hover {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen4_nextD.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-image: url(:/prefijoNuevo/IMAGENES_creador/imagen5_nextE.png);\n"
"}\n"
"")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.listWidget_panelPreguntas.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bel_respondioEl.setText(_translate("Form", "Lo que es"))
        self.bel_respondioYo.setText(_translate("Form", "Yo respondi"))
        self.bel_califFinal.setText(_translate("Form", "Calificacion final"))
        self.btn_terminar.setText(_translate("Form", "Terminar"))
        self.bel_punteroPregunta.setText(_translate("Form", "10"))
        self.label_2.setText(_translate("Form", "/"))
        self.bel_noPreguntas.setText(_translate("Form", "105"))
import IMAG_rc
