# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modRespMultiples_d.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(915, 559)
        self.listWidget_panelVersion = QtWidgets.QStackedWidget(Form)
        self.listWidget_panelVersion.setGeometry(QtCore.QRect(0, 60, 901, 491))
        self.listWidget_panelVersion.setToolTipDuration(0)
        self.listWidget_panelVersion.setStyleSheet("")
        self.listWidget_panelVersion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelVersion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelVersion.setObjectName("listWidget_panelVersion")
        self.btn_pregImag100 = QtWidgets.QPushButton(Form)
        self.btn_pregImag100.setGeometry(QtCore.QRect(170, 20, 31, 31))
        self.btn_pregImag100.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_preg100.png);")
        self.btn_pregImag100.setText("")
        self.btn_pregImag100.setObjectName("btn_pregImag100")
        self.btn_pregImag75 = QtWidgets.QPushButton(Form)
        self.btn_pregImag75.setGeometry(QtCore.QRect(130, 20, 31, 31))
        self.btn_pregImag75.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_preg75.png);")
        self.btn_pregImag75.setText("")
        self.btn_pregImag75.setObjectName("btn_pregImag75")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(240, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(780, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeEdit.setCurrentSectionIndex(0)
        self.timeEdit.setObjectName("timeEdit")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(40, 50, 841, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(780, 0, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn_pregAND = QtWidgets.QPushButton(Form)
        self.btn_pregAND.setGeometry(QtCore.QRect(230, 20, 51, 31))
        self.btn_pregAND.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_and.png);")
        self.btn_pregAND.setText("")
        self.btn_pregAND.setObjectName("btn_pregAND")
        self.btn_pregOR = QtWidgets.QPushButton(Form)
        self.btn_pregOR.setGeometry(QtCore.QRect(290, 20, 41, 31))
        self.btn_pregOR.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_or.png);")
        self.btn_pregOR.setText("")
        self.btn_pregOR.setObjectName("btn_pregOR")
        self.dSpin_pregTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_pregTam.setGeometry(QtCore.QRect(510, 20, 69, 26))
        self.dSpin_pregTam.setObjectName("dSpin_pregTam")
        self.btn_pregCen = QtWidgets.QPushButton(Form)
        self.btn_pregCen.setGeometry(QtCore.QRect(450, 20, 21, 21))
        self.btn_pregCen.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_centrar.png);")
        self.btn_pregCen.setText("")
        self.btn_pregCen.setProperty("id", 0)
        self.btn_pregCen.setObjectName("btn_pregCen")
        self.btn_respIzq = QtWidgets.QPushButton(Form)
        self.btn_respIzq.setGeometry(QtCore.QRect(595, 20, 21, 21))
        self.btn_respIzq.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_izquierda.png);")
        self.btn_respIzq.setText("")
        self.btn_respIzq.setObjectName("btn_respIzq")
        self.btn_respDer = QtWidgets.QPushButton(Form)
        self.btn_respDer.setGeometry(QtCore.QRect(660, 20, 21, 21))
        self.btn_respDer.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_derecho.png);")
        self.btn_respDer.setText("")
        self.btn_respDer.setObjectName("btn_respDer")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(440, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dSpin_respTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_respTam.setGeometry(QtCore.QRect(690, 20, 69, 26))
        self.dSpin_respTam.setObjectName("dSpin_respTam")
        self.btn_respCen = QtWidgets.QPushButton(Form)
        self.btn_respCen.setGeometry(QtCore.QRect(630, 20, 21, 21))
        self.btn_respCen.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_centrar.png);")
        self.btn_respCen.setText("")
        self.btn_respCen.setObjectName("btn_respCen")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(620, 0, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_pregIzq = QtWidgets.QPushButton(Form)
        self.btn_pregIzq.setGeometry(QtCore.QRect(420, 20, 21, 21))
        self.btn_pregIzq.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_izquierda.png);")
        self.btn_pregIzq.setText("")
        self.btn_pregIzq.setProperty("id", 1)
        self.btn_pregIzq.setObjectName("btn_pregIzq")
        self.btn_pregDer = QtWidgets.QPushButton(Form)
        self.btn_pregDer.setGeometry(QtCore.QRect(480, 20, 21, 21))
        self.btn_pregDer.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/alinear_derecho.png);")
        self.btn_pregDer.setText("")
        self.btn_pregDer.setProperty("id", 2)
        self.btn_pregDer.setObjectName("btn_pregDer")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_pregImag0 = QtWidgets.QPushButton(Form)
        self.btn_pregImag0.setGeometry(QtCore.QRect(50, 20, 31, 31))
        self.btn_pregImag0.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_preg0.png);")
        self.btn_pregImag0.setText("")
        self.btn_pregImag0.setObjectName("btn_pregImag0")
        self.btn_pregImag50 = QtWidgets.QPushButton(Form)
        self.btn_pregImag50.setGeometry(QtCore.QRect(90, 20, 31, 31))
        self.btn_pregImag50.setStyleSheet("border-image: url(:/CreadorPreguntas/IMAGENES/icon_preg50.png);")
        self.btn_pregImag50.setText("")
        self.btn_pregImag50.setObjectName("btn_pregImag50")

        self.retranslateUi(Form)
        self.listWidget_panelVersion.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Tipo de pregunta"))
        self.timeEdit.setDisplayFormat(_translate("Form", "mm:ss"))
        self.label_11.setText(_translate("Form", "Tiempo de pregunta"))
        self.label_10.setText(_translate("Form", "Posicion pregunta"))
        self.label_12.setText(_translate("Form", "Posicion respuesta"))
        self.label_5.setText(_translate("Form", "Incluir imagenes"))

import IMAG_rc
