# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicioSesion_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(318, 499)
        Dialog.setMaximumSize(QtCore.QSize(356, 570))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setMinimumSize(QtCore.QSize(0, 10))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setMinimumSize(QtCore.QSize(10, 0))
        self.label_20.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.bel_fotoPerfil = QtWidgets.QLabel(Dialog)
        self.bel_fotoPerfil.setMinimumSize(QtCore.QSize(250, 220))
        self.bel_fotoPerfil.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bel_fotoPerfil.setStyleSheet("border: 1px solid black;\n"
"border-radius:5px;")
        self.bel_fotoPerfil.setText("")
        self.bel_fotoPerfil.setObjectName("bel_fotoPerfil")
        self.horizontalLayout_11.addWidget(self.bel_fotoPerfil)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setMinimumSize(QtCore.QSize(10, 0))
        self.label_22.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setMinimumSize(QtCore.QSize(0, 10))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setMinimumSize(QtCore.QSize(71, 17))
        self.label_17.setMaximumSize(QtCore.QSize(71, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.comBox_nombres = QtWidgets.QComboBox(Dialog)
        self.comBox_nombres.setMinimumSize(QtCore.QSize(0, 35))
        self.comBox_nombres.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comBox_nombres.setFont(font)
        self.comBox_nombres.setStyleSheet("border: 1px solid black;\n"
"border-radius:2px;\n"
"font-size: 17px;")
        self.comBox_nombres.setObjectName("comBox_nombres")
        self.horizontalLayout_10.addWidget(self.comBox_nombres)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setMinimumSize(QtCore.QSize(0, 5))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setMinimumSize(QtCore.QSize(71, 17))
        self.label_13.setMaximumSize(QtCore.QSize(71, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.edit_clave = QtWidgets.QLineEdit(Dialog)
        self.edit_clave.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_clave.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_clave.setFont(font)
        self.edit_clave.setStyleSheet("border: 1px solid black;\n"
"border-radius:2px;")
        self.edit_clave.setMaxLength(20)
        self.edit_clave.setObjectName("edit_clave")
        self.horizontalLayout_9.addWidget(self.edit_clave, 0, QtCore.Qt.AlignVCenter)
        self.btn_mostrarPassword = QtWidgets.QPushButton(Dialog)
        self.btn_mostrarPassword.setMinimumSize(QtCore.QSize(41, 31))
        self.btn_mostrarPassword.setMaximumSize(QtCore.QSize(41, 31))
        self.btn_mostrarPassword.setStyleSheet("")
        self.btn_mostrarPassword.setText("")
        self.btn_mostrarPassword.setObjectName("btn_mostrarPassword")
        self.horizontalLayout_9.addWidget(self.btn_mostrarPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.btn_iniciarSesion = QtWidgets.QPushButton(Dialog)
        self.btn_iniciarSesion.setMinimumSize(QtCore.QSize(300, 40))
        self.btn_iniciarSesion.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_iniciarSesion.setStyleSheet("\n"
"QPushButton {\n"
"/*border: 1px solid black;*/\n"
"border-radius:5px;\n"
"background-color: rgb(94, 236, 215);\n"
"color:white;\n"
"font-size: 17px;\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-radius:5px;\n"
"background-color: rgb(113, 209, 174);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-radius:5px;\n"
"background-color: rgb(101, 189, 193);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_iniciarSesion.setObjectName("btn_iniciarSesion")
        self.verticalLayout.addWidget(self.btn_iniciarSesion)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.btn_passwordOlvidado = QtWidgets.QCommandLinkButton(Dialog)
        self.btn_passwordOlvidado.setMinimumSize(QtCore.QSize(210, 30))
        self.btn_passwordOlvidado.setMaximumSize(QtCore.QSize(210, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_passwordOlvidado.setFont(font)
        self.btn_passwordOlvidado.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_passwordOlvidado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_passwordOlvidado.setStyleSheet("color: rgb(33, 73, 255);")
        icon = QtGui.QIcon.fromTheme("?")
        self.btn_passwordOlvidado.setIcon(icon)
        self.btn_passwordOlvidado.setAutoDefault(False)
        self.btn_passwordOlvidado.setDefault(False)
        self.btn_passwordOlvidado.setDescription("")
        self.btn_passwordOlvidado.setObjectName("btn_passwordOlvidado")
        self.horizontalLayout_8.addWidget(self.btn_passwordOlvidado)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.btn_registrar = QtWidgets.QPushButton(Dialog)
        self.btn_registrar.setMinimumSize(QtCore.QSize(300, 40))
        self.btn_registrar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_registrar.setStyleSheet("\n"
"QPushButton {\n"
"/*border: 1px solid black;*/\n"
"border-radius:5px;\n"
"background-color: rgb(180, 177, 193);\n"
"color:white;\n"
"font-size: 17px;\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-radius:5px;\n"
"background-color: rgb(158, 153, 156);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-radius:5px;\n"
"background-color: rgb(175, 203, 216);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_registrar.setObjectName("btn_registrar")
        self.verticalLayout.addWidget(self.btn_registrar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "Nombre:"))
        self.label_13.setText(_translate("Dialog", "Clave:"))
        self.btn_iniciarSesion.setText(_translate("Dialog", "Entrar"))
        self.btn_passwordOlvidado.setText(_translate("Dialog", "¿Olvidaste tu contraseña?"))
        self.btn_registrar.setText(_translate("Dialog", "Crear una cuenta"))
