# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'olvidoContrasena_d.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(257, 270)
        Dialog.setMinimumSize(QtCore.QSize(257, 260))
        Dialog.setMaximumSize(QtCore.QSize(280, 295))
        Dialog.setMouseTracking(False)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(False)
        Dialog.setWindowTitle("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setMinimumSize(QtCore.QSize(0, 5))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 7))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.bel_mensaje = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.bel_mensaje.setFont(font)
        self.bel_mensaje.setStyleSheet("")
        self.bel_mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.bel_mensaje.setWordWrap(True)
        self.bel_mensaje.setObjectName("bel_mensaje")
        self.verticalLayout.addWidget(self.bel_mensaje)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(20, 10))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.le_mejorAmigo = QtWidgets.QLineEdit(Dialog)
        self.le_mejorAmigo.setMinimumSize(QtCore.QSize(0, 35))
        self.le_mejorAmigo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_mejorAmigo.setFont(font)
        self.le_mejorAmigo.setStyleSheet("border: 1px solid black;\n"
"border-radius:2px;")
        self.le_mejorAmigo.setMaxLength(20)
        self.le_mejorAmigo.setAlignment(QtCore.Qt.AlignCenter)
        self.le_mejorAmigo.setObjectName("le_mejorAmigo")
        self.horizontalLayout_9.addWidget(self.le_mejorAmigo)
        self.btn_mostrarPassword = QtWidgets.QPushButton(Dialog)
        self.btn_mostrarPassword.setMinimumSize(QtCore.QSize(41, 31))
        self.btn_mostrarPassword.setMaximumSize(QtCore.QSize(41, 31))
        self.btn_mostrarPassword.setStyleSheet("")
        self.btn_mostrarPassword.setText("")
        self.btn_mostrarPassword.setObjectName("btn_mostrarPassword")
        self.horizontalLayout_9.addWidget(self.btn_mostrarPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(20, 10))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.btn_entrar = QtWidgets.QPushButton(Dialog)
        self.btn_entrar.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_entrar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_entrar.setStyleSheet("\n"
"QPushButton {\n"
"/*border: 1px solid black;*/\n"
"border-radius:5px;\n"
"background-color: rgb(180, 177, 193);\n"
"color:white;\n"
"font-size: 17px;\n"
" }\n"
"\n"
"QPushButton:hover {\n"
"border-radius:5px;\n"
"background-color: rgb(158, 153, 156);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-radius:5px;\n"
"background-color: rgb(175, 203, 216);\n"
"font-size: 17px;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_entrar.setObjectName("btn_entrar")
        self.verticalLayout.addWidget(self.btn_entrar)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.btn_amigoOlvidado = QtWidgets.QCommandLinkButton(Dialog)
        self.btn_amigoOlvidado.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_amigoOlvidado.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_amigoOlvidado.setFont(font)
        self.btn_amigoOlvidado.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_amigoOlvidado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_amigoOlvidado.setStyleSheet("color: rgb(33, 73, 255);")
        icon = QtGui.QIcon.fromTheme("?")
        self.btn_amigoOlvidado.setIcon(icon)
        self.btn_amigoOlvidado.setAutoDefault(False)
        self.btn_amigoOlvidado.setDefault(False)
        self.btn_amigoOlvidado.setDescription("")
        self.btn_amigoOlvidado.setObjectName("btn_amigoOlvidado")
        self.horizontalLayout_8.addWidget(self.btn_amigoOlvidado)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(20, 10))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.bel_mensaje.setText(_translate("Dialog", "Hola: Jorge,no te preocupes si has olvidado tu contraseña, podras  entrar a tu cuenta  ingresando el nombre de tu mejor amigo."))
        self.btn_entrar.setText(_translate("Dialog", "Hecho"))
        self.btn_amigoOlvidado.setText(_translate("Dialog", "Ups lo olvide n.n"))
