# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creadorPreguntasMain_d.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 513)
        self.scroll_barra = QtWidgets.QScrollArea(Form)
        self.scroll_barra.setGeometry(QtCore.QRect(10, 110, 81, 361))
        self.scroll_barra.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_barra.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_barra.setWidgetResizable(True)
        self.scroll_barra.setObjectName("scroll_barra")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 65, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_barra.setWidget(self.scrollAreaWidgetContents)
        self.listWidget_panelPreguntas = QtWidgets.QStackedWidget(Form)
        self.listWidget_panelPreguntas.setGeometry(QtCore.QRect(100, 100, 861, 401))
        self.listWidget_panelPreguntas.setToolTipDuration(0)
        self.listWidget_panelPreguntas.setStyleSheet("padding:0px;\n"
"border: 1px solid red;\n"
"")
        self.listWidget_panelPreguntas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelPreguntas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelPreguntas.setObjectName("listWidget_panelPreguntas")
        self.btn_pregImag0 = QtWidgets.QPushButton(Form)
        self.btn_pregImag0.setGeometry(QtCore.QRect(100, 10, 71, 61))
        self.btn_pregImag0.setStyleSheet("border-image: url(:/alinear/IMAGENES/imagen_0.png);")
        self.btn_pregImag0.setText("")
        self.btn_pregImag0.setObjectName("btn_pregImag0")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 70, 81, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_pregImag50 = QtWidgets.QPushButton(Form)
        self.btn_pregImag50.setGeometry(QtCore.QRect(200, 20, 51, 41))
        self.btn_pregImag50.setStyleSheet("border-image: url(:/alinear/IMAGENES/imagen_50.png);")
        self.btn_pregImag50.setText("")
        self.btn_pregImag50.setObjectName("btn_pregImag50")
        self.btn_pregImag100 = QtWidgets.QPushButton(Form)
        self.btn_pregImag100.setGeometry(QtCore.QRect(290, 10, 61, 51))
        self.btn_pregImag100.setStyleSheet("border-image: url(:/alinear/IMAGENES/imagen_100.png);")
        self.btn_pregImag100.setText("")
        self.btn_pregImag100.setObjectName("btn_pregImag100")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 81, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(900, 10, 71, 61))
        self.pushButton_5.setStyleSheet("border-image: url(:/alinear/IMAGENES/pregunta_delete.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.btn_mas = QtWidgets.QPushButton(Form)
        self.btn_mas.setGeometry(QtCore.QRect(750, 10, 71, 61))
        self.btn_mas.setStyleSheet("border-image: url(:/alinear/IMAGENES/pregunta_add.png);")
        self.btn_mas.setText("")
        self.btn_mas.setObjectName("btn_mas")
        self.btn__ver = QtWidgets.QPushButton(Form)
        self.btn__ver.setGeometry(QtCore.QRect(820, 10, 71, 61))
        self.btn__ver.setStyleSheet("border-image: url(:/alinear/IMAGENES/pregunta_ver.png);")
        self.btn__ver.setText("")
        self.btn__ver.setObjectName("btn__ver")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(760, 70, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(830, 70, 51, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(900, 70, 61, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(680, 70, 61, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_guardar = QtWidgets.QPushButton(Form)
        self.btn_guardar.setGeometry(QtCore.QRect(680, 20, 61, 51))
        self.btn_guardar.setStyleSheet("border-image: url(:/alinear/IMAGENES/pregunta_guardar.png);")
        self.btn_guardar.setText("")
        self.btn_guardar.setObjectName("btn_guardar")

        self.retranslateUi(Form)
        self.listWidget_panelPreguntas.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Sin imagen"))
        self.label_2.setText(_translate("Form", "0.5 imagen"))
        self.label_3.setText(_translate("Form", "1.0 imagen"))
        self.label_4.setText(_translate("Form", "mas"))
        self.label_5.setText(_translate("Form", "ver"))
        self.label_6.setText(_translate("Form", "eliminar"))
        self.label_7.setText(_translate("Form", "Guardar"))

import imagenes_rc
