# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreadorPreguntasMain_d.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_panelPreguntas = QtWidgets.QStackedWidget(self.centralwidget)
        self.listWidget_panelPreguntas.setGeometry(QtCore.QRect(110, 10, 911, 551))
        self.listWidget_panelPreguntas.setToolTipDuration(0)
        self.listWidget_panelPreguntas.setStyleSheet("")
        self.listWidget_panelPreguntas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelPreguntas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelPreguntas.setObjectName("listWidget_panelPreguntas")
        self.scroll_barra = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_barra.setGeometry(QtCore.QRect(10, 100, 91, 431))
        self.scroll_barra.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_barra.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_barra.setWidgetResizable(True)
        self.scroll_barra.setObjectName("scroll_barra")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 75, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_barra.setWidget(self.scrollAreaWidgetContents)
        self.btn_mas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mas.setGeometry(QtCore.QRect(30, 20, 51, 41))
        self.btn_mas.setStyleSheet("border-image: url(:/alinear/IMAGENES/pregunta_add.png);")
        self.btn_mas.setText("")
        self.btn_mas.setObjectName("btn_mas")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 22))
        self.menubar.setObjectName("menubar")
        self.menuNueva_pregunta = QtWidgets.QMenu(self.menubar)
        self.menuNueva_pregunta.setObjectName("menuNueva_pregunta")
        self.menuCuestionario = QtWidgets.QMenu(self.menubar)
        self.menuCuestionario.setObjectName("menuCuestionario")
        self.menuCompartir = QtWidgets.QMenu(self.menubar)
        self.menuCompartir.setObjectName("menuCompartir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCrear_nueva_pregunta = QtWidgets.QAction(MainWindow)
        self.actionCrear_nueva_pregunta.setObjectName("actionCrear_nueva_pregunta")
        self.actionEliminar_una_pregunta = QtWidgets.QAction(MainWindow)
        self.actionEliminar_una_pregunta.setObjectName("actionEliminar_una_pregunta")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionCambiar_nombre = QtWidgets.QAction(MainWindow)
        self.actionCambiar_nombre.setObjectName("actionCambiar_nombre")
        self.actionVisualizar = QtWidgets.QAction(MainWindow)
        self.actionVisualizar.setObjectName("actionVisualizar")
        self.actionSubir_a_DelphiData = QtWidgets.QAction(MainWindow)
        self.actionSubir_a_DelphiData.setObjectName("actionSubir_a_DelphiData")
        self.actionMandar_por_correo = QtWidgets.QAction(MainWindow)
        self.actionMandar_por_correo.setObjectName("actionMandar_por_correo")
        self.actionEjecutar_cuestionario = QtWidgets.QAction(MainWindow)
        self.actionEjecutar_cuestionario.setObjectName("actionEjecutar_cuestionario")
        self.actionGuarda_en_otra_carpeta = QtWidgets.QAction(MainWindow)
        self.actionGuarda_en_otra_carpeta.setObjectName("actionGuarda_en_otra_carpeta")
        self.menuNueva_pregunta.addAction(self.actionCrear_nueva_pregunta)
        self.menuNueva_pregunta.addAction(self.actionEliminar_una_pregunta)
        self.menuNueva_pregunta.addAction(self.actionVisualizar)
        self.menuCuestionario.addAction(self.actionGuardar)
        self.menuCuestionario.addAction(self.actionCambiar_nombre)
        self.menuCuestionario.addAction(self.actionEjecutar_cuestionario)
        self.menuCompartir.addSeparator()
        self.menuCompartir.addAction(self.actionSubir_a_DelphiData)
        self.menuCompartir.addSeparator()
        self.menuCompartir.addAction(self.actionMandar_por_correo)
        self.menuCompartir.addAction(self.actionGuarda_en_otra_carpeta)
        self.menubar.addAction(self.menuCuestionario.menuAction())
        self.menubar.addAction(self.menuNueva_pregunta.menuAction())
        self.menubar.addAction(self.menuCompartir.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget_panelPreguntas.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Agregar otra\n"
"pregunta"))
        self.menuNueva_pregunta.setTitle(_translate("MainWindow", "Preguntas"))
        self.menuCuestionario.setTitle(_translate("MainWindow", "Cuestionario"))
        self.menuCompartir.setTitle(_translate("MainWindow", "Compartir"))
        self.actionCrear_nueva_pregunta.setText(_translate("MainWindow", "Crear"))
        self.actionEliminar_una_pregunta.setText(_translate("MainWindow", "Eliminar"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar "))
        self.actionCambiar_nombre.setText(_translate("MainWindow", "Cambiar nombre"))
        self.actionVisualizar.setText(_translate("MainWindow", "Visualizar "))
        self.actionSubir_a_DelphiData.setText(_translate("MainWindow", "Subir a DelphiData"))
        self.actionMandar_por_correo.setText(_translate("MainWindow", "Mandar por correo"))
        self.actionEjecutar_cuestionario.setText(_translate("MainWindow", "Ejecutar cuestionario"))
        self.actionGuarda_en_otra_carpeta.setText(_translate("MainWindow", "Guarda en otra carpeta"))

import imagenes_rc
