# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modRespMultiples_d.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(915, 623)
        self.listWidget_panelVersion = QtWidgets.QStackedWidget(Form)
        self.listWidget_panelVersion.setGeometry(QtCore.QRect(10, 70, 901, 541))
        self.listWidget_panelVersion.setToolTipDuration(0)
        self.listWidget_panelVersion.setStyleSheet("padding:0px;\n"
"border: 1px solid red;\n"
"")
        self.listWidget_panelVersion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_panelVersion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget_panelVersion.setObjectName("listWidget_panelVersion")
        self.btn_pregImag0 = QtWidgets.QPushButton(Form)
        self.btn_pregImag0.setGeometry(QtCore.QRect(630, 20, 51, 51))
        self.btn_pregImag0.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_preg0.png);")
        self.btn_pregImag0.setText("")
        self.btn_pregImag0.setObjectName("btn_pregImag0")
        self.btn_pregImag50 = QtWidgets.QPushButton(Form)
        self.btn_pregImag50.setGeometry(QtCore.QRect(700, 20, 51, 51))
        self.btn_pregImag50.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_preg50.png);")
        self.btn_pregImag50.setText("")
        self.btn_pregImag50.setObjectName("btn_pregImag50")
        self.btn_pregImag75 = QtWidgets.QPushButton(Form)
        self.btn_pregImag75.setGeometry(QtCore.QRect(760, 20, 51, 51))
        self.btn_pregImag75.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_preg75.png);")
        self.btn_pregImag75.setText("")
        self.btn_pregImag75.setObjectName("btn_pregImag75")
        self.btn_pregImag100 = QtWidgets.QPushButton(Form)
        self.btn_pregImag100.setGeometry(QtCore.QRect(830, 20, 51, 51))
        self.btn_pregImag100.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_preg100.png);")
        self.btn_pregImag100.setText("")
        self.btn_pregImag100.setObjectName("btn_pregImag100")
        self.dSpin_pregTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_pregTam.setGeometry(QtCore.QRect(360, 30, 69, 26))
        self.dSpin_pregTam.setObjectName("dSpin_pregTam")
        self.btn_pregDer = QtWidgets.QPushButton(Form)
        self.btn_pregDer.setGeometry(QtCore.QRect(330, 30, 21, 21))
        self.btn_pregDer.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_derecho.png);")
        self.btn_pregDer.setText("")
        self.btn_pregDer.setProperty("id", 2)
        self.btn_pregDer.setObjectName("btn_pregDer")
        self.btn_pregCen = QtWidgets.QPushButton(Form)
        self.btn_pregCen.setGeometry(QtCore.QRect(300, 30, 21, 21))
        self.btn_pregCen.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_centrar.png);")
        self.btn_pregCen.setText("")
        self.btn_pregCen.setProperty("id", 0)
        self.btn_pregCen.setObjectName("btn_pregCen")
        self.btn_pregIzq = QtWidgets.QPushButton(Form)
        self.btn_pregIzq.setGeometry(QtCore.QRect(270, 30, 21, 21))
        self.btn_pregIzq.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_izquierda.png);")
        self.btn_pregIzq.setText("")
        self.btn_pregIzq.setProperty("id", 1)
        self.btn_pregIzq.setObjectName("btn_pregIzq")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeEdit.setFont(font)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeEdit.setCurrentSectionIndex(0)
        self.timeEdit.setObjectName("timeEdit")
        self.btn_pregOR = QtWidgets.QPushButton(Form)
        self.btn_pregOR.setGeometry(QtCore.QRect(210, 30, 41, 31))
        self.btn_pregOR.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_or.png);")
        self.btn_pregOR.setText("")
        self.btn_pregOR.setObjectName("btn_pregOR")
        self.btn_pregAND = QtWidgets.QPushButton(Form)
        self.btn_pregAND.setGeometry(QtCore.QRect(150, 30, 51, 31))
        self.btn_pregAND.setStyleSheet("border-image: url(:/alinear/ICONOS/icon_and.png);")
        self.btn_pregAND.setText("")
        self.btn_pregAND.setObjectName("btn_pregAND")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 0, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(290, 0, 141, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(690, 0, 141, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(150, 0, 121, 21))
        self.label_6.setObjectName("label_6")
        self.btn_respCen = QtWidgets.QPushButton(Form)
        self.btn_respCen.setGeometry(QtCore.QRect(490, 30, 21, 21))
        self.btn_respCen.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_centrar.png);")
        self.btn_respCen.setText("")
        self.btn_respCen.setObjectName("btn_respCen")
        self.btn_respIzq = QtWidgets.QPushButton(Form)
        self.btn_respIzq.setGeometry(QtCore.QRect(455, 30, 21, 21))
        self.btn_respIzq.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_izquierda.png);")
        self.btn_respIzq.setText("")
        self.btn_respIzq.setObjectName("btn_respIzq")
        self.dSpin_respTam = QtWidgets.QDoubleSpinBox(Form)
        self.dSpin_respTam.setGeometry(QtCore.QRect(550, 30, 69, 26))
        self.dSpin_respTam.setObjectName("dSpin_respTam")
        self.btn_respDer = QtWidgets.QPushButton(Form)
        self.btn_respDer.setGeometry(QtCore.QRect(520, 30, 21, 21))
        self.btn_respDer.setStyleSheet("border-image: url(:/alinear/IMAGENES/alinear_derecho.png);")
        self.btn_respDer.setText("")
        self.btn_respDer.setObjectName("btn_respDer")

        self.retranslateUi(Form)
        self.listWidget_panelVersion.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timeEdit.setDisplayFormat(_translate("Form", "mm:ss"))
        self.label_3.setText(_translate("Form", "Posicion respuestas"))
        self.label_4.setText(_translate("Form", "Posicion pregunta"))
        self.label_5.setText(_translate("Form", "Incluir imagenes"))
        self.label_6.setText(_translate("Form", "Tipo de pregunta"))

import imagenes_rc
