# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InteractuadorCuestionarios_d.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 408)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.btn_proceso = QtWidgets.QPushButton(Form)
        self.btn_proceso.setMinimumSize(QtCore.QSize(33, 35))
        self.btn_proceso.setMaximumSize(QtCore.QSize(33, 35))
        self.btn_proceso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_proceso.setMouseTracking(False)
        self.btn_proceso.setTabletTracking(False)
        self.btn_proceso.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_folder.png);\n"
"")
        self.btn_proceso.setText("")
        self.btn_proceso.setObjectName("btn_proceso")
        self.verticalLayout_5.addWidget(self.btn_proceso)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.btn_descargados = QtWidgets.QPushButton(Form)
        self.btn_descargados.setMinimumSize(QtCore.QSize(34, 32))
        self.btn_descargados.setMaximumSize(QtCore.QSize(34, 32))
        self.btn_descargados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_descargados.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icons8-downloads-folder-40.png);")
        self.btn_descargados.setText("")
        self.btn_descargados.setObjectName("btn_descargados")
        self.verticalLayout_4.addWidget(self.btn_descargados)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.btn_nuevo = QtWidgets.QPushButton(Form)
        self.btn_nuevo.setMinimumSize(QtCore.QSize(31, 31))
        self.btn_nuevo.setMaximumSize(QtCore.QSize(31, 31))
        self.btn_nuevo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nuevo.setStyleSheet("border-image: url(:/prefijoNuevo/IMAGENES_creador/icon_newCuestionario.png);")
        self.btn_nuevo.setText("")
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.verticalLayout_3.addWidget(self.btn_nuevo)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setMaximumSize(QtCore.QSize(20, 20))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QStackedWidget(Form)
        self.listWidget.setMinimumSize(QtCore.QSize(400, 250))
        self.listWidget.setToolTipDuration(0)
        self.listWidget.setStyleSheet("")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(Form)
        self.listWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "En proceso"))
        self.label_15.setText(_translate("Form", "Descargados"))
        self.label_14.setText(_translate("Form", "Nuevo"))
import IMAG_rc
